namespace NetEvolve.Analyzer.Helpers;

using System;
using System.Collections.Immutable;

/// <summary>
/// The complete set of C# keywords, mirroring
/// <see href="https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/"/>, split into
/// <see cref="ReservedKeywords"/> (always keywords) and <see cref="ContextualKeywords"/> (keywords only in
/// specific syntactic positions, and otherwise valid identifiers).
/// </summary>
internal static class CSharpKeywords
{
    /// <summary>
    /// Keywords that are reserved everywhere; an identifier with the same spelling requires the <c>@</c>
    /// prefix (<c>@class</c>).
    /// </summary>
    public static readonly ImmutableHashSet<string> ReservedKeywords = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while"
    );

    /// <summary>
    /// Keywords that carry special meaning only in specific syntactic contexts (query clauses, patterns,
    /// declarations); the same spelling is a valid identifier everywhere else.
    /// </summary>
    public static readonly ImmutableHashSet<string> ContextualKeywords = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "add",
        "alias",
        "and",
        "ascending",
        "args",
        "async",
        "await",
        "by",
        "descending",
        "dynamic",
        "equals",
        "file",
        "from",
        "get",
        "global",
        "group",
        "init",
        "into",
        "join",
        "let",
        "managed",
        "nameof",
        "nint",
        "not",
        "notnull",
        "nuint",
        "on",
        "or",
        "orderby",
        "partial",
        "record",
        "remove",
        "required",
        "scoped",
        "select",
        "set",
        "unmanaged",
        "value",
        "var",
        "when",
        "where",
        "with",
        "yield"
    );
}
