namespace NetEvolve.Analyzer.Tests.Unit.Style;

using System;
using System.Threading.Tasks;
using NetEvolve.Analyzer.Style;
using NetEvolve.Analyzer.Tests.Unit.Verifiers;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

/// <summary>Unit tests for <see cref="UseNumericLiteralSuffixOverCastAnalyzer"/> (NE0013).</summary>
public sealed class UseNumericLiteralSuffixOverCastAnalyzerTests
{
    [Test]
    public async Task Initialize_NullContext_ThrowsArgumentNullException()
    {
        var analyzer = new UseNumericLiteralSuffixOverCastAnalyzer();
        ArgumentNullException? caught = null;

        try
        {
            analyzer.Initialize(null!);
        }
        catch (ArgumentNullException exception)
        {
            caught = exception;
        }

        await Assert.That(caught).IsNotNull();
    }

    // ---- Type axis: every suffixable type, cast in a field initializer ---------------------------------

    [Test]
    [Arguments("long", "0")]
    [Arguments("ulong", "0")]
    [Arguments("uint", "0")]
    [Arguments("float", "1")]
    [Arguments("double", "1")]
    [Arguments("decimal", "10")]
    public Task CastToSuffixableType_FieldInitializer_ReportsDiagnostic(string type, string literal) =>
        CSharpAnalyzerVerifier<UseNumericLiteralSuffixOverCastAnalyzer>.VerifyAnalyzerAsync(
            $$"""
            public sealed class Sample
            {
                public {{type}} Value = {|NE0013:({{type}}){{literal}}|};
            }
            """
        );

    // ---- Context axis: a fixed `(long)0` cast, across every syntactic context it can appear in ----------

    [Test]
    [Arguments(
        """
            public sealed class Sample
            {
                public long Value = {|NE0013:(long)0|};
            }
            """
    )]
    [Arguments(
        """
            public sealed class Sample
            {
                public void Run()
                {
                    long value = {|NE0013:(long)0|};
                }
            }
            """
    )]
    [Arguments(
        """
            public sealed class Sample
            {
                public void Run() => Consume({|NE0013:(long)0|});

                private static void Consume(long value) { }
            }
            """
    )]
    [Arguments(
        """
            public sealed class Sample
            {
                public void Run(long value)
                {
                    if (value == {|NE0013:(long)0|})
                    {
                    }
                }
            }
            """
    )]
    [Arguments(
        """
            public sealed class Sample
            {
                public long GetValue() => {|NE0013:(long)0|};
            }
            """
    )]
    public Task CastToLong_VariousContexts_ReportsDiagnostic(string source) =>
        CSharpAnalyzerVerifier<UseNumericLiteralSuffixOverCastAnalyzer>.VerifyAnalyzerAsync(source);

    // ---- Negative cases ---------------------------------------------------------------------------------

    [Test]
    [Arguments(
        // No suffix exists for `int`.
        """
            public sealed class Sample
            {
                public int Value = (int)0;
            }
            """
    )]
    [Arguments(
        // Literal already has a suffix.
        """
            public sealed class Sample
            {
                public long Value = (long)0L;
            }
            """
    )]
    [Arguments(
        // Fractional literal — rewriting could change the value once the cast's rounding is gone.
        """
            public sealed class Sample
            {
                public long Value = (long)1.5;
            }
            """
    )]
    [Arguments(
        // Hex literal cast to a floating/decimal type can't be marked with that type's suffix.
        """
            public sealed class Sample
            {
                public double Value = (double)0x10;
            }
            """
    )]
    [Arguments(
        // Cast expression isn't a literal.
        """
            public sealed class Sample
            {
                public long Value = (long)GetValue();

                private static int GetValue() => 0;
            }
            """
    )]
    [Arguments(
        // Generated code is skipped.
        """
            // <auto-generated/>
            public sealed class Sample
            {
                public long Value = (long)0;
            }
            """
    )]
    public Task NegativeCases_ReportsNothing(string source) =>
        CSharpAnalyzerVerifier<UseNumericLiteralSuffixOverCastAnalyzer>.VerifyAnalyzerAsync(source);

    // ---- Hex literal cast to an integer type is still suffixable ----------------------------------------

    [Test]
    public Task CastToHexToLong_ReportsDiagnostic() =>
        CSharpAnalyzerVerifier<UseNumericLiteralSuffixOverCastAnalyzer>.VerifyAnalyzerAsync(
            """
            public sealed class Sample
            {
                public long Value = {|NE0013:(long)0x10|};
            }
            """
        );
}
