namespace NetEvolve.Analyzer.Tests.Integration.Maintainability;

using System;
using System.Linq;
using System.Threading.Tasks;
using NetEvolve.Analyzer;
using NetEvolve.Analyzer.Maintainability;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

/// <summary>
/// End-to-end tests for NE0001 through the real <see cref="Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers"/>
/// pipeline, covering the parts the unit verifier cannot reach: an absent file path and generated-code skipping.
/// </summary>
public sealed class OneTypePerFileAnalyzerTests
{
    private const string TwoTypes = """
        namespace Geometry;

        public sealed class Circle { }

        public sealed class Square { }
        """;

    private static bool IsNe0001(Microsoft.CodeAnalysis.Diagnostic diagnostic) =>
        string.Equals(diagnostic.Id, DiagnosticIds.NE0001, StringComparison.Ordinal);

    [Test]
    public async Task Violation_WithFilePath_ReportsNe0001()
    {
        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(TwoTypes, new OneTypePerFileAnalyzer(), path: "Shapes.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Count(IsNe0001)).IsEqualTo(2);
    }

    [Test]
    public async Task Compliant_SingleMatchingType_ReportsNothing()
    {
        const string source = """
            namespace Geometry;

            public sealed class Circle { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(source, new OneTypePerFileAnalyzer(), path: "Circle.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task WithoutFilePath_ReportsNothing()
    {
        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(TwoTypes, new OneTypePerFileAnalyzer())
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task GeneratedFileByName_IsSkipped()
    {
        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(TwoTypes, new OneTypePerFileAnalyzer(), path: "Shapes.designer.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task GeneratedFileByHeader_IsSkipped()
    {
        const string source = """
            // <auto-generated/>
            namespace Geometry;

            public sealed class Circle { }

            public sealed class Square { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(source, new OneTypePerFileAnalyzer(), path: "Shapes.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task FileScopedType_MismatchedName_IsIgnored()
    {
        const string source = """
            namespace Geometry;

            public sealed class Circle { }

            file sealed class Helper { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(source, new OneTypePerFileAnalyzer(), path: "Circle.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task PartialType_SuffixedFileName_ReportsNothing()
    {
        const string source = """
            namespace Geometry;

            public sealed partial class Circle { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(source, new OneTypePerFileAnalyzer(), path: "Circle.Drawing.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }

    [Test]
    public async Task NonPartialType_SuffixedFileName_ReportsNe0001()
    {
        const string source = """
            namespace Geometry;

            public sealed class Circle { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(source, new OneTypePerFileAnalyzer(), path: "Circle.Drawing.cs")
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsTrue();
    }

    [Test]
    public async Task GroupGenericOverloads_Property_SuppressesArityViolation()
    {
        const string source = """
            namespace Geometry;

            public readonly struct Result { }

            public readonly struct Result<T> { }
            """;

        var diagnostics = await AnalyzerCompiler
            .GetAnalyzerDiagnosticsAsync(
                source,
                new OneTypePerFileAnalyzer(),
                path: "Result.cs",
                properties: [("NetEvolveAnalyzerGroupGenericOverloads", "true")]
            )
            .ConfigureAwait(false);

        await Assert.That(diagnostics.Any(IsNe0001)).IsFalse();
    }
}
